---
server:
  port: 52000
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: GMT+8
  freemarker:
    charset: UTF-8
    cache: false
    content-type: text/html
    template-loader-path: classpath:/template
    suffix: .html
    check-template-location: true
    enabled: false
  application:
    name: PinTiDuo-service
  data:
    jpa:
      repositories:
        enabled: true
#datasource:  
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://qdm176766154.my3w.com:3306/qdm176766154_db?characterEncoding=UTF-8
    #username: qdm176766154
    #password: chenerping
  datasource:  
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chen?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    open-in-view: true 
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      redisson-config: classpath:conf/redisson.yaml
      hibernate:
        cache:
          use_structured_entries: true
          use_second_level_cache: true
          region_prefix: hibernate
          region:
            factory_class: org.hibernate.cache.redis.hibernate52.SingletonRedisRegionFactory
          use_query_cache: true
        generate_statistics: false
      redis:
        expiryInSeconds:
          default: 120
          hibernate:
            common: 0
            account: 1200
  redis:
    database: 2
    port: 6379
    expire: 1800
    host: localhost
com:
  zhiyong:
    resourcePathMap: /**->classpath:/static/,/u/**->D:/mooc3/rs200/u/

eureka:
  server:
    enable-self-preservation: false        # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 5000       # 
  instance:
    hostname: www.zymoocs.com
    appname: PinTiDuo-service
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client: 
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:7888/eureka/
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000


